# Generated by Django 4.2.23 on 2026-05-13 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Email do usuário convidado', max_length=254, verbose_name='Email')),
                ('role', models.CharField(choices=[('MASTER', 'Master (administra tudo da empresa)'), ('ADMIN', 'Admin (gerencia usuários/permissões da empresa)'), ('MEMBER', 'Membro (acesso padrão)'), ('VIEWER', 'Somente leitura')], help_text='Papel que o usuário terá na empresa ao aceitar o convite', max_length=10, verbose_name='Papel')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Token único para validação do convite (UUID4)', unique=True, verbose_name='Token')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACCEPTED', 'Aceito'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado')], db_index=True, default='PENDING', help_text='Estado atual do convite', max_length=10, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do convite', verbose_name='Criado em')),
                ('expira_em', models.DateTimeField(help_text='Data e hora de expiração do convite', verbose_name='Expira em')),
                ('aceito_em', models.DateTimeField(blank=True, help_text='Data e hora em que o convite foi aceito', null=True, verbose_name='Aceito em')),
                ('cancelado_em', models.DateTimeField(blank=True, help_text='Data e hora em que o convite foi cancelado', null=True, verbose_name='Cancelado em')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Endereço IP do usuário que aceitou o convite', null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device do usuário que aceitou o convite', verbose_name='User Agent')),
                ('tentativas_envio', models.PositiveSmallIntegerField(default=1, help_text='Número de vezes que o email foi enviado (original + reenvios)', verbose_name='Tentativas de envio')),
                ('ultimo_envio_em', models.DateTimeField(blank=True, help_text='Data e hora do último envio do email', null=True, verbose_name='Último envio em')),
                ('convidado_por', models.ForeignKey(blank=True, help_text='Usuário que criou o convite (MASTER/ADMIN)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Convidado por')),
                ('empresa', models.ForeignKey(help_text='Empresa para a qual o usuário está sendo convidado', on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='usuarios.empresa', verbose_name='Empresa')),
                ('usuario_criado', models.ForeignKey(blank=True, help_text='Usuário que foi criado ao aceitar este convite', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_aceitos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário criado')),
            ],
            options={
                'verbose_name': 'Convite',
                'verbose_name_plural': 'Convites',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='idx_convite_empresa_status'), models.Index(fields=['email', 'empresa'], name='idx_convite_email_empresa'), models.Index(fields=['token'], name='idx_convite_token'), models.Index(fields=['status', 'expira_em'], name='idx_convite_status_expira')],
            },
        ),
        migrations.AddConstraint(
            model_name='convite',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('empresa', 'email'), name='uq_convite_pendente_email_empresa', violation_error_message='Já existe um convite pendente para este email nesta empresa.'),
        ),
    ]
