# Generated by Django 4.2.23 on 2026-09-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='documentos_habilitados',
            field=models.BooleanField(default=False, help_text='Libera o upload de documentos de DF para esta empresa. Ligar somente após o contrato de operador (DPA) estar assinado.'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='quota_documentos_gb',
            field=models.PositiveIntegerField(default=50, help_text='Limite de armazenamento de documentos, em GB. 0 = sem limite.'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='retencao_anos',
            field=models.PositiveSmallIntegerField(default=5, help_text='Anos de guarda dos documentos após o fim do exercício a que pertencem.'),
        ),
    ]
