# Generated by Django 4.2.23 on 2026-05-18 18:26

from django.db import migrations, models
import django.db.models.deletion


def associar_mapeamentos_empresa(apps, schema_editor):
    """
    Data migration: associa todos os MapeamentoContas existentes à empresa
    com CNPJ 11111111111111 (Empresa para o teste que estou fazendo LTDA).
    
    Busca pelo CNPJ ao invés de ID fixo, garantindo funcionamento em qualquer ambiente.
    """
    Empresa = apps.get_model('usuarios', 'Empresa')
    MapeamentoContas = apps.get_model('df', 'MapeamentoContas')
    
    # Buscar empresa pelo CNPJ (não pelo ID, que pode variar entre ambientes)
    cnpj_teste = '11111111111111'
    
    try:
        empresa = Empresa.objects.get(cnpj=cnpj_teste)
    except Empresa.DoesNotExist:
        raise Exception(
            f"\n{'='*60}\n"
            f"❌ ERRO: Empresa com CNPJ {cnpj_teste} não encontrada!\n\n"
            f"Antes de rodar esta migration, crie a empresa:\n"
            f"  Nome: Empresa para o teste que estou fazendo LTDA\n"
            f"  CNPJ: {cnpj_teste}\n"
            f"\nComando sugerido:\n"
            f"  python manage.py shell -c \"from usuarios.models import Empresa; "
            f"Empresa.objects.create(nome='Empresa para o teste que estou fazendo LTDA', "
            f"cnpj='{cnpj_teste}')\"\n"
            f"{'='*60}\n"
        )
    
    # Associar todos os mapeamentos à empresa
    count = MapeamentoContas.objects.filter(empresa__isnull=True).update(empresa=empresa)
    
    print(f"✓ {count} mapeamentos associados à empresa '{empresa.nome}' (ID {empresa.id})")


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('df', '0008_remove_balanceteitem_uq_balancete_fundo_ano_conta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapeamentocontas',
            options={'ordering': ['empresa', 'grupo_pequeno', 'conta'], 'verbose_name': 'Mapeamento de CC', 'verbose_name_plural': 'Mapeamentos de CC'},
        ),
        # Adiciona campo empresa como nullable temporariamente
        migrations.AddField(
            model_name='mapeamentocontas',
            name='empresa',
            field=models.ForeignKey(
                help_text='Empresa (tenant) proprietária deste mapeamento.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='mapeamentos_contas',
                to='usuarios.empresa',
                null=True,  # Temporariamente nullable para permitir data migration
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name='mapeamentocontas',
            name='conta',
            field=models.CharField(max_length=30),
        ),
        # Data migration: associar mapeamentos existentes à empresa pelo CNPJ
        migrations.RunPython(
            associar_mapeamentos_empresa,
            reverse_code=migrations.RunPython.noop,
        ),
        # Tornar empresa obrigatória após data migration
        migrations.AlterField(
            model_name='mapeamentocontas',
            name='empresa',
            field=models.ForeignKey(
                help_text='Empresa (tenant) proprietária deste mapeamento.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='mapeamentos_contas',
                to='usuarios.empresa',
                db_index=True,
            ),
        ),
        migrations.AddIndex(
            model_name='mapeamentocontas',
            index=models.Index(fields=['empresa', 'conta'], name='idx_map_empresa_conta'),
        ),
        migrations.AddConstraint(
            model_name='mapeamentocontas',
            constraint=models.UniqueConstraint(fields=('empresa', 'conta'), name='uq_mapeamento_empresa_conta'),
        ),
    ]
