# Generated by Django 4.2.23 on 2026-06-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0009_alter_mapeamentocontas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundo',
            name='data_vencimento_df',
            field=models.DateField(blank=True, help_text='Data de vencimento anual da DF (apenas dia e mês são considerados, repete anualmente)', null=True, verbose_name='Data de Vencimento da DF'),
        ),
    ]
