# Generated by Django 4.2.23 on 2026-06-08 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_convite_convite_uq_convite_pendente_email_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('df', '0010_fundo_data_vencimento_df'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundo',
            name='tipo_df',
            field=models.CharField(blank=True, choices=[('anual', 'Anual'), ('transitoria', 'Transitória'), ('trimestral', 'Trimestral'), ('encerramento', 'Encerramento')], help_text='Tipo de Demonstração Financeira do fundo', max_length=20, null=True, verbose_name='Tipo de DF'),
        ),
        migrations.CreateModel(
            name='HistoricoEmissaoDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data e hora em que a DF foi gerada/baixada')),
                ('data_referencia_df', models.DateField(db_index=True, help_text='Data de referência (saldo atual) da DF gerada')),
                ('data_anterior_df', models.DateField(blank=True, help_text='Data anterior (comparação) da DF gerada, ou None se zerado', null=True)),
                ('tipo_exportacao', models.CharField(choices=[('excel', 'Excel'), ('word', 'Word'), ('visualizacao', 'Visualização')], help_text='Formato de exportação ou se foi apenas visualização', max_length=20)),
                ('empresa', models.ForeignKey(help_text='Empresa (tenant) - para facilitar queries por escopo', on_delete=django.db.models.deletion.CASCADE, related_name='historico_emissoes_df', to='usuarios.empresa')),
                ('fundo', models.ForeignKey(help_text='Fundo para o qual a DF foi emitida', on_delete=django.db.models.deletion.CASCADE, related_name='historico_emissoes', to='df.fundo')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário que gerou/baixou a DF', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emissoes_df', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Emissão de DF',
                'verbose_name_plural': 'Históricos de Emissões de DFs',
                'ordering': ['-data_emissao'],
                'indexes': [models.Index(fields=['empresa', 'fundo', '-data_emissao'], name='idx_hist_emp_fundo_data'), models.Index(fields=['fundo', 'data_referencia_df'], name='idx_hist_fundo_ref')],
            },
        ),
    ]
