# Generated by Django 4.2.23 on 2026-06-08 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_convite_convite_uq_convite_pendente_email_empresa'),
        ('df', '0011_fundo_tipo_df_historicoemissaodf'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_periodo', models.CharField(choices=[('trimestral', 'Trimestral'), ('anual', 'Anual'), ('transitoria', 'Transitória'), ('encerramento', 'Encerramento')], help_text='Tipo deste período', max_length=20)),
                ('ano', models.IntegerField(help_text='Ano do período (ex: 2025)')),
                ('trimestre', models.IntegerField(blank=True, help_text='Número do trimestre (1-4) para tipo trimestral, null para outros', null=True)),
                ('data_vencimento', models.DateField(help_text='Data de vencimento deste período')),
                ('data_referencia', models.DateField(blank=True, help_text='Data de referência (saldo atual) quando dados são importados', null=True)),
                ('data_anterior', models.DateField(blank=True, help_text='Data anterior (saldo comparação) ou null para zerado', null=True)),
                ('status', models.CharField(choices=[('nao_iniciada', 'Não Iniciada'), ('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada'), ('vencida', 'Vencida')], default='nao_iniciada', help_text='Status atual do período', max_length=20)),
                ('criado_manualmente', models.BooleanField(default=False, help_text='True para Transitória/Encerramento criados pelo usuário')),
                ('descricao', models.CharField(blank=True, help_text='Descrição opcional para períodos manuais', max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(help_text='Empresa (tenant) - facilita queries por escopo', on_delete=django.db.models.deletion.CASCADE, related_name='periodos_df', to='usuarios.empresa')),
                ('fundo', models.ForeignKey(help_text='Fundo ao qual este período pertence', on_delete=django.db.models.deletion.CASCADE, related_name='periodos_df', to='df.fundo')),
            ],
            options={
                'verbose_name': 'Período de DF',
                'verbose_name_plural': 'Períodos de DFs',
                'ordering': ['empresa', 'fundo', '-ano', '-trimestre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos_ativos', models.JSONField(default=list, help_text="Lista de tipos de DF ativos: ['trimestral', 'anual', 'transitoria', 'encerramento']")),
                ('trim1_dia', models.IntegerField(blank=True, help_text='Dia do vencimento do 1º trimestre (1-31)', null=True)),
                ('trim1_mes', models.IntegerField(blank=True, help_text='Mês do vencimento do 1º trimestre (1-12)', null=True)),
                ('trim2_dia', models.IntegerField(blank=True, help_text='Dia do vencimento do 2º trimestre (1-31)', null=True)),
                ('trim2_mes', models.IntegerField(blank=True, help_text='Mês do vencimento do 2º trimestre (1-12)', null=True)),
                ('trim3_dia', models.IntegerField(blank=True, help_text='Dia do vencimento do 3º trimestre (1-31)', null=True)),
                ('trim3_mes', models.IntegerField(blank=True, help_text='Mês do vencimento do 3º trimestre (1-12)', null=True)),
                ('trim4_dia', models.IntegerField(blank=True, help_text='Dia do vencimento do 4º trimestre (1-31)', null=True)),
                ('trim4_mes', models.IntegerField(blank=True, help_text='Mês do vencimento do 4º trimestre (1-12)', null=True)),
                ('anual_dia', models.IntegerField(blank=True, help_text='Dia do vencimento anual (1-31)', null=True)),
                ('anual_mes', models.IntegerField(blank=True, help_text='Mês do vencimento anual (1-12)', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fundo', models.OneToOneField(help_text='Fundo ao qual esta configuração pertence', on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_df', to='df.fundo')),
            ],
            options={
                'verbose_name': 'Configuração de DF',
                'verbose_name_plural': 'Configurações de DFs',
            },
        ),
        migrations.AddField(
            model_name='balanceteitem',
            name='periodo_df',
            field=models.ForeignKey(blank=True, help_text='Período de DF ao qual estes dados pertencem (null para dados legados)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balancete_items', to='df.periododf'),
        ),
        migrations.AddField(
            model_name='historicoemissaodf',
            name='periodo_df',
            field=models.ForeignKey(blank=True, help_text='Período de DF ao qual esta emissão pertence (null para emissões legadas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_emissoes', to='df.periododf'),
        ),
        migrations.AddField(
            model_name='mecitem',
            name='periodo_df',
            field=models.ForeignKey(blank=True, help_text='Período de DF ao qual estes dados pertencem (null para dados legados)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mec_items', to='df.periododf'),
        ),
        migrations.AddIndex(
            model_name='periododf',
            index=models.Index(fields=['empresa', 'fundo', 'ano'], name='idx_periodo_emp_fundo_ano'),
        ),
        migrations.AddIndex(
            model_name='periododf',
            index=models.Index(fields=['fundo', 'ano', 'tipo_periodo'], name='idx_periodo_fundo_ano_tipo'),
        ),
        migrations.AddIndex(
            model_name='periododf',
            index=models.Index(fields=['status', 'data_vencimento'], name='idx_periodo_status_venc'),
        ),
        migrations.AddConstraint(
            model_name='periododf',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo_periodo__in', ['trimestral', 'anual'])), fields=('fundo', 'tipo_periodo', 'ano', 'trimestre'), name='uq_periodo_fundo_tipo_ano_tri'),
        ),
    ]
