# Generated by Django 4.2.23 on 2026-06-08 19:19

from django.db import migrations


def migrate_fundo_to_configuracaodf(apps, schema_editor):
    """
    Migra dados dos campos tipo_df e data_vencimento_df do modelo Fundo
    para o modelo ConfiguracaoDF.
    """
    Fundo = apps.get_model('df', 'Fundo')
    ConfiguracaoDF = apps.get_model('df', 'ConfiguracaoDF')
    
    for fundo in Fundo.objects.all():
        # Pular se já existe configuração
        if hasattr(fundo, 'configuracao_df') and fundo.configuracao_df:
            continue
        
        tipos_ativos = []
        config_data = {
            'fundo': fundo,
            'tipos_ativos': [],
        }
        
        # Migrar tipo_df se existir
        if fundo.tipo_df:
            tipos_ativos.append(fundo.tipo_df)
        
        # Migrar data_vencimento_df se existir e se tipo for anual
        if fundo.data_vencimento_df and fundo.tipo_df == 'anual':
            config_data['anual_dia'] = fundo.data_vencimento_df.day
            config_data['anual_mes'] = fundo.data_vencimento_df.month
        
        # Só criar ConfiguracaoDF se houver pelo menos um tipo ativo
        if tipos_ativos:
            config_data['tipos_ativos'] = tipos_ativos
            ConfiguracaoDF.objects.create(**config_data)


def reverse_migration(apps, schema_editor):
    """
    Não há necessidade de reverter dados, apenas deletar ConfiguracaoDF
    criadas pela migração se necessário.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0012_periododf_configuracaodf_balanceteitem_periodo_df_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_fundo_to_configuracaodf, reverse_migration),
    ]
