# Generated by Django 4.2.23 on 2026-06-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0013_migrate_fundo_to_configuracaodf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundo',
            name='data_vencimento_df',
        ),
        migrations.RemoveField(
            model_name='fundo',
            name='tipo_df',
        ),
    ]
