# Generated by Django 4.2.23 on 2026-06-18 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_convite_convite_uq_convite_pendente_email_empresa'),
        ('df', '0015_redesign_configuracaodf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestoras', to='usuarios.empresa')),
            ],
            options={
                'verbose_name': 'Gestora',
                'verbose_name_plural': 'Gestoras',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='fundo',
            name='gestora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundos', to='df.gestora'),
        ),
        migrations.AddConstraint(
            model_name='gestora',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='uq_gestora_empresa_nome'),
        ),
        migrations.AddConstraint(
            model_name='gestora',
            constraint=models.UniqueConstraint(fields=('empresa', 'cnpj'), name='uq_gestora_empresa_cnpj'),
        ),
    ]
