# Generated by Django 4.2.23 on 2026-06-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0019_simplify_periododf'),
    ]

    operations = [
        migrations.AddField(
            model_name='periododf',
            name='notificado_1',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='periododf',
            name='notificado_15',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='periododf',
            name='notificado_30',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='periododf',
            name='notificado_60',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='periododf',
            name='notificado_90',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='periododf',
            name='tipo_periodo',
            field=models.CharField(choices=[('anual', 'Anual'), ('transitoria', 'Transitória'), ('encerramento', 'Encerramento')], help_text='Tipo deste período', max_length=20),
        ),
    ]
