# Generated by Django 4.2.23 on 2026-06-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0016_add_gestora_model_and_fundo_fk'),
        ('df', '0020_periododf_notificacoes'),
    ]

    operations = [
    ]
