# Generated by Django 4.2.23 on 2026-07-07 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0021_merge_20260624_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundo',
            name='tipo_fundo',
            field=models.CharField(choices=[('FIDC', 'FIDC'), ('FIF', 'FIF'), ('FII', 'FII'), ('FIP', 'FIP')], db_index=True, default='FIDC', help_text='Tipo do fundo — define qual checklist de documentos padrão é aplicado.', max_length=10),
        ),
        migrations.CreateModel(
            name='ChecklistItemPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fundo', models.CharField(choices=[('FIDC', 'FIDC'), ('FIF', 'FIF'), ('FII', 'FII'), ('FIP', 'FIP')], db_index=True, help_text='Tipo de fundo ao qual este item de checklist padrão se aplica.', max_length=10)),
                ('secao', models.CharField(blank=True, default='', max_length=120)),
                ('texto', models.CharField(max_length=255)),
                ('prazo', models.CharField(blank=True, default='', max_length=120)),
                ('responsavel', models.CharField(blank=True, default='', max_length=120)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Item de Checklist Padrão',
                'verbose_name_plural': 'Itens de Checklist Padrão',
                'ordering': ['tipo_fundo', 'ordem'],
                'indexes': [models.Index(fields=['tipo_fundo', 'ordem'], name='idx_checklist_padrao_tipo')],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao', models.CharField(blank=True, default='', max_length=120)),
                ('texto', models.CharField(max_length=255)),
                ('prazo', models.CharField(blank=True, default='', max_length=120)),
                ('responsavel', models.CharField(blank=True, default='', max_length=120)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('recebido', models.BooleanField(default=False)),
                ('periodo_df', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='df.periododf')),
            ],
            options={
                'verbose_name': 'Item de Checklist do Período',
                'verbose_name_plural': 'Itens de Checklist do Período',
                'ordering': ['periodo_df', 'ordem'],
                'indexes': [models.Index(fields=['periodo_df', 'recebido'], name='idx_checklist_periodo_recebido')],
            },
        ),
    ]
