# Generated by Django 4.2.23 on 2026-06-29 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_convite_convite_uq_convite_pendente_email_empresa'),
        ('df', '0021_merge_20260624_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItemPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_itens_padrao', to='usuarios.empresa')),
            ],
            options={
                'verbose_name': 'Item de Checklist Padrão',
                'verbose_name_plural': 'Itens de Checklist Padrão',
                'ordering': ['empresa', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('recebido', models.BooleanField(default=False)),
                ('periodo_df', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='df.periododf')),
            ],
            options={
                'verbose_name': 'Item de Checklist do Período',
                'verbose_name_plural': 'Itens de Checklist do Período',
                'ordering': ['periodo_df', 'ordem'],
                'indexes': [models.Index(fields=['periodo_df', 'recebido'], name='idx_checklist_periodo_recebido')],
            },
        ),
    ]
