# Generated by Django 4.2.23 on 2026-09-14 17:38

import df.models
import df.storages
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0005_empresa_documentos_habilitados_and_more'),
        ('df', '0023_seed_checklist_padrao_por_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_texto', models.CharField(blank=True, default='', help_text='Snapshot do texto do item no momento do upload — usado para re-vincular o documento por texto quando o checklist é resincronizado.', max_length=255)),
                ('arquivo', models.FileField(max_length=500, storage=df.storages.documentos_storage, upload_to=df.models.documento_df_upload_to)),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('contem_dados_pessoais', models.BooleanField(default=False, help_text='Arquivo contém dados pessoais de terceiros (ex.: kits cadastrais de cotistas). Usado para localizar PII em pedidos de titular (LGPD).')),
                ('retencao_ate', models.DateField(blank=True, help_text='Data a partir da qual o documento pode ser expurgado.', null=True)),
                ('enviado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('excluido_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('checklist_item', models.ForeignKey(blank=True, help_text='Item de checklist ao qual este arquivo está vinculado, se houver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='df.checklistitemperiodo')),
                ('empresa', models.ForeignKey(help_text='Empresa (tenant) - para facilitar queries por escopo', on_delete=django.db.models.deletion.CASCADE, related_name='documentos_df', to='usuarios.empresa')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL)),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_excluidos', to=settings.AUTH_USER_MODEL)),
                ('periodo_df', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='df.periododf')),
            ],
            options={
                'verbose_name': 'Documento da DF',
                'verbose_name_plural': 'Documentos da DF',
                'ordering': ['-enviado_em'],
                'indexes': [models.Index(fields=['periodo_df', 'excluido_em'], name='idx_doc_periodo_ativo'), models.Index(fields=['empresa', 'excluido_em'], name='idx_doc_empresa_ativo'), models.Index(fields=['empresa', 'retencao_ate'], name='idx_doc_retencao')],
            },
        ),
    ]
