# Generated by Django 4.2.23 on 2026-09-14 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_empresa_documentos_habilitados_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('df', '0024_documentodf'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAcessoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_id_hist', models.BigIntegerField(help_text='Id do documento no momento do evento — sobrevive mesmo se o documento for expurgado fisicamente e o FK acima virar NULL.', null=True)),
                ('acao', models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('exclusao', 'Exclusão'), ('negado', 'Acesso negado')], db_index=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('ocorrido_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acesso', to='df.documentodf')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_acesso_documentos', to='usuarios.empresa')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acesso_documentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acesso a Documento',
                'verbose_name_plural': 'Logs de Acesso a Documentos',
                'ordering': ['-ocorrido_em'],
                'indexes': [models.Index(fields=['documento', '-ocorrido_em'], name='idx_logacesso_doc_data'), models.Index(fields=['empresa', '-ocorrido_em'], name='idx_logacesso_emp_data')],
            },
        ),
    ]
