# Generated by Django 4.2.23 on 2026-09-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df', '0026_backfill_retencao_ate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logacessodocumento',
            name='acao',
            field=models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('exclusao', 'Exclusão'), ('negado', 'Acesso negado'), ('expurgo', 'Expurgo físico')], db_index=True, max_length=20),
        ),
    ]
