# Generated by Django 4.2.23 on 2026-10-05 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_empresa_documentos_habilitados_and_more'),
        ('df', '0027_alter_logacessodocumento_acao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentodf',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa (tenant) - para facilitar queries por escopo', on_delete=django.db.models.deletion.PROTECT, related_name='documentos_df', to='usuarios.empresa'),
        ),
        migrations.AlterField(
            model_name='documentodf',
            name='periodo_df',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='df.periododf'),
        ),
    ]
